package cn.zhouyafeng.blog.entity;

import java.util.Date;

public class BlogEntity {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_blog.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_blog.blog_title
     *
     * @mbggenerated
     */
    private String blogTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_blog.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_blog.modify_time
     *
     * @mbggenerated
     */
    private Date modifyTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_blog.blog_type
     *
     * @mbggenerated
     */
    private String blogType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_blog.blog_tag
     *
     * @mbggenerated
     */
    private String blogTag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_blog.music
     *
     * @mbggenerated
     */
    private String music;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_blog.reading_count
     *
     * @mbggenerated
     */
    private Integer readingCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column blog_blog.blog_content
     *
     * @mbggenerated
     */
    private String blogContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_blog.id
     *
     * @return the value of blog_blog.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_blog.id
     *
     * @param id the value for blog_blog.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_blog.blog_title
     *
     * @return the value of blog_blog.blog_title
     *
     * @mbggenerated
     */
    public String getBlogTitle() {
        return blogTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_blog.blog_title
     *
     * @param blogTitle the value for blog_blog.blog_title
     *
     * @mbggenerated
     */
    public void setBlogTitle(String blogTitle) {
        this.blogTitle = blogTitle == null ? null : blogTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_blog.update_time
     *
     * @return the value of blog_blog.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_blog.update_time
     *
     * @param updateTime the value for blog_blog.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_blog.modify_time
     *
     * @return the value of blog_blog.modify_time
     *
     * @mbggenerated
     */
    public Date getModifyTime() {
        return modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_blog.modify_time
     *
     * @param modifyTime the value for blog_blog.modify_time
     *
     * @mbggenerated
     */
    public void setModifyTime(Date modifyTime) {
        this.modifyTime = modifyTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_blog.blog_type
     *
     * @return the value of blog_blog.blog_type
     *
     * @mbggenerated
     */
    public String getBlogType() {
        return blogType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_blog.blog_type
     *
     * @param blogType the value for blog_blog.blog_type
     *
     * @mbggenerated
     */
    public void setBlogType(String blogType) {
        this.blogType = blogType == null ? null : blogType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_blog.blog_tag
     *
     * @return the value of blog_blog.blog_tag
     *
     * @mbggenerated
     */
    public String getBlogTag() {
        return blogTag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_blog.blog_tag
     *
     * @param blogTag the value for blog_blog.blog_tag
     *
     * @mbggenerated
     */
    public void setBlogTag(String blogTag) {
        this.blogTag = blogTag == null ? null : blogTag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_blog.music
     *
     * @return the value of blog_blog.music
     *
     * @mbggenerated
     */
    public String getMusic() {
        return music;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_blog.music
     *
     * @param music the value for blog_blog.music
     *
     * @mbggenerated
     */
    public void setMusic(String music) {
        this.music = music == null ? null : music.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_blog.reading_count
     *
     * @return the value of blog_blog.reading_count
     *
     * @mbggenerated
     */
    public Integer getReadingCount() {
        return readingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_blog.reading_count
     *
     * @param readingCount the value for blog_blog.reading_count
     *
     * @mbggenerated
     */
    public void setReadingCount(Integer readingCount) {
        this.readingCount = readingCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column blog_blog.blog_content
     *
     * @return the value of blog_blog.blog_content
     *
     * @mbggenerated
     */
    public String getBlogContent() {
        return blogContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column blog_blog.blog_content
     *
     * @param blogContent the value for blog_blog.blog_content
     *
     * @mbggenerated
     */
    public void setBlogContent(String blogContent) {
        this.blogContent = blogContent == null ? null : blogContent.trim();
    }
}