package cn.zhouyafeng.blog.dao;

import cn.zhouyafeng.blog.entity.CommentEntity;
import cn.zhouyafeng.blog.entity.CommentEntityWithBLOBs;

public interface CommentEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_comment
     *
     * @mbggenerated
     */
    int insert(CommentEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_comment
     *
     * @mbggenerated
     */
    int insertSelective(CommentEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_comment
     *
     * @mbggenerated
     */
    CommentEntityWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CommentEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(CommentEntityWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table blog_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CommentEntity record);
}