package cn.zhouyafeng.blog.dao;

import cn.zhouyafeng.blog.entity.SubCommentEntity;

public interface SubCommentEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_comment
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_comment
     *
     * @mbggenerated
     */
    int insert(SubCommentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_comment
     *
     * @mbggenerated
     */
    int insertSelective(SubCommentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_comment
     *
     * @mbggenerated
     */
    SubCommentEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SubCommentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKeyWithBLOBs(SubCommentEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sub_comment
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SubCommentEntity record);
}